-- CreateTable
CREATE TABLE `ligabelanda` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nama` VARCHAR(50) NOT NULL,
    `umur` INTEGER NOT NULL,
    `posisi` VARCHAR(4) NOT NULL,
    `NA` VARCHAR(50) NOT NULL,
    `KA` VARCHAR(100) NOT NULL,
    `KSI` VARCHAR(100) NOT NULL,
    `harga` VARCHAR(100) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ligainggris` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nama` VARCHAR(50) NOT NULL,
    `umur` INTEGER NOT NULL,
    `posisi` VARCHAR(4) NOT NULL,
    `NA` VARCHAR(50) NOT NULL,
    `KA` VARCHAR(100) NOT NULL,
    `KSI` VARCHAR(100) NOT NULL,
    `harga` VARCHAR(100) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ligajerman` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nama` VARCHAR(50) NOT NULL,
    `umur` INTEGER NOT NULL,
    `posisi` VARCHAR(4) NOT NULL,
    `NA` VARCHAR(50) NOT NULL,
    `KA` VARCHAR(100) NOT NULL,
    `KSI` VARCHAR(100) NOT NULL,
    `harga` VARCHAR(100) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ligaprancis` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nama` VARCHAR(50) NOT NULL,
    `umur` INTEGER NOT NULL,
    `posisi` VARCHAR(4) NOT NULL,
    `NA` VARCHAR(50) NOT NULL,
    `KA` VARCHAR(100) NOT NULL,
    `KSI` VARCHAR(100) NOT NULL,
    `harga` VARCHAR(100) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ligaspanyol` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nama` VARCHAR(50) NOT NULL,
    `umur` INTEGER NOT NULL,
    `posisi` VARCHAR(4) NOT NULL,
    `NA` VARCHAR(50) NOT NULL,
    `KA` VARCHAR(100) NOT NULL,
    `KSI` VARCHAR(100) NOT NULL,
    `harga` VARCHAR(100) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
